repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      exclude: ^.*\b(migrations)\b.*$

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
